### ISSUE TITLE
Some problems about the Linux image

### ISSUE THREAD

**Issue by wuqiulin1995** [ucare-uchicago/femu#1]
Hi!

I'm building the FEMU environment, and I want to know where to download your VM image.

Thanks a lot!

                                                                                           Qiulin

**Comment by huaicheng** [comment]
Hi,

Could you send me an email about this? I will provide you a link for downloading the VM image.

**Comment by huaicheng** [comment]
In order to not burden our server with excessive traffic, I didn't put the link into README file.  You can drop me an email about this. I will provide the link
