### ISSUE TITLE
Whether femu implements erase

### ISSUE THREAD

**Issue by leafworld** [ucare-uchicago/femu#10]
Whether femu implements the erase function？I built an erase command myself. 
tgt_submit_erase(545);
tgt_submit_read(545); ==> output is 0
tgt_submit_write(545, 6);// write 6 into the page
tgt_submit_read(545); ==> output is 6, is ok
tgt_submit_erase(545);
tgt_submit_read(545); ==> output is still 6 , there??
I don't know whether femu didn't implement erase, or my code has a problem. thank you~

**Comment by huaicheng** [comment]
Currently FEMU only implements erase caused delay, data won't be erased.

But this is a good point, I will add a fix for this. Thanks for reporting this!
