### ISSUE TITLE
How can I get 99.99th latency?

### ISSUE THREAD

**Issue by codezero759** [ucare-uchicago/femu#13]
My question is below.

- Can you let me know how to measure 99.99th long tail latency? 
- Is it possible to measure latency of each I/O?

Is it right that latency measurements in femu are made by recording in specific memory rather than delaying through 'sleep' command? I want to know exactly how measurements are made in femu.

**Comment by huaicheng** [comment]
>  Can you let me know how to measure 99.99th long tail latency?
>  Is it possible to measure latency of each I/O?

In your guest OS, you can run IO benchmark tools (e.g. FIO) to measure per-IO latencies (by enabling the per-IO latency log option "write_lat_log"), then you can calculate the CDF by yourself (e.g. I have a some tool here for that purpose: https://github.com/huaicheng/rtk). FIO output also contains some predefined percentiles. 

> Is it right that latency measurements in femu are made by recording in specific memory rather than delaying through 'sleep' command? I want to know exactly how measurements are made in femu.

In general, FEMU emulates IO delay transparent to the applications running in the guest OS. FEMU delay each IO for a certain amount of time before it returns the IO back to guest OS. The time to delay is decided by the FTL logic based on NAND latencies and queueing delays.

**Comment by codezero759** [comment]
thank you for your reply!
