### ISSUE TITLE
unable to see large difference in kvm_exit with/without doorbell in guest

### ISSUE THREAD

**Issue by shehbazj** [ucare-uchicago/femu#15]
Hello FEMU Experts,

First of all, thank you for building and open-sourcing your work!

I trying to understand the overhead of doorbell that you cite in your FAST paper. I do random writes of small sizes on a OC-SSD target. I run this with and without the 1 LOC addition (return false) that you describe in "tweaking Guest linux" sub-section of README. I see a very small difference in the number of kvm_exit events. I would like to ask the approximate ratio/frequency of drop in vm exits you obtained with/without guest modification?

Steps to reproduce:

1) run FEMU in "whitebox" mode using Ubuntu 16.04 guest VM and an NVMe disk
2) compile and build latest linux kernel - v 5.0.0+.
3) create a nvme device using nvme-cli that supports liblightnvm

> sudo nvme lnvm create -d nvme0n1 -n pblkdev -t pblk -b 0 -e 7

4) in host terminal, run perf tool to count number of kvm_exit events:

> sudo perf record -e kvm:kvm_exit -ag

5) in guest, run the following 
for i in `shuf -i 1-10000 -n 10000`; 
do 
         dd if=/dev/zero of=/dev/nvme0n1 bs=4096 count=1 seek=$i; 
done

6) stop perf tool and run report:

> sudo perf report  -n

Now, make change in 

> nvme_dbbuf_update_and_check_event()

7) recompile, reboot. re-run perf record in host. re-run random write in guest. terminate perf record in host. get perf report.

The number of guest exits I get for MSR_WRITE events:

with doorbell : 690050
without doorbell : 691373

Is this normal? is there any other way to detect how many guest exits were limited after making the tweak you describe in the guest OS?

Thanks again for your help!

**Comment by huaicheng** [comment]
Hi,

That one line change in guest kernel is to help achieve ZERO doorbell overhead (from guest side). Without guest kernel change, FEMU already utilizes NVMe shadow doorbell buffer to reduce MOST of MMIO doorbell writes. For a fair comparison, you need to compare FEMU with a vanilla QEMU NVMe. We suggest that one liner change for tail-sensitive workloads.

**Comment by shehbazj** [comment]
Thank you for your reply.
I am happy to report that I am now observing about 2.5X less kvm_exits with FEMU as compared to raw QEMU nvme device. 
Marking the issue closed.
