### ISSUE TITLE
Disable or redirect femu debug outputs

### ISSUE THREAD

**Issue by IcicleF** [ucare-uchicago/femu#18]
Hi. Thanks for creating this software first.
I launched `run-blackbox.sh` and noticed that debug outputs like `ppn[-1] not mapped` and some GC info are printed directly to ttyS0, mixing with the VM output.
Is there any way to disable all of them or redirect them to another place?

Thanks in advance.

**Comment by huaicheng** [comment]
You can comment out the corresponding `printf()` in `hw/block/ssd/ftl.c` Line 305 and recompile FEMU to get rid of it.

**Comment by IcicleF** [comment]
Thanks for your quick reply!
Unfortunately this is not the only one. For example it is observed that `printf` at `hw/block/ssd/ftl_gc_manager.c` Line 155 will also print to terminal.
There are many other `printf` calls in source files in `hw/block/ssd`. Is it that I should comment out all of them?
Thank you in advance.

**Comment by huaicheng** [comment]
Many `printf()`s are not in the hot path (for debugging purpose) and they're not being triggered very often. Depending on what you want to achieve, you can comment out all of them.

You can also simply redirect all the output into a log file, add "> log 2>&1" at the end of `qemu` command line in the VM script.

**Comment by IcicleF** [comment]
It's very helpful.
Thank you very much.
