### ISSUE TITLE
memfd_create declared twice error 

### ISSUE THREAD

**Issue by BrightSirius** [ucare-uchicago/femu#2]
The compile-time error occurs on my Ubuntu18.04 as follows:
```
/home/sirius/labs-proj/femu/util/memfd.c:40:12: error: static declaration of ‘memfd_create’ follows non-static declaration
 static int memfd_create(const char *name, unsigned int flags)
            ^~~~~~~~~~~~
In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:115:0,
                 from /usr/include/x86_64-linux-gnu/bits/mman.h:45,
                 from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
                 from /home/sirius/labs-proj/femu/include/sysemu/os-posix.h:29,
                 from /home/sirius/labs-proj/femu/include/qemu/osdep.h:104,
                 from /home/sirius/labs-proj/femu/util/memfd.c:28:
/usr/include/x86_64-linux-gnu/bits/mman-shared.h:46:5: note: previous declaration of ‘memfd_create’ was here
 int memfd_create (const char *__name, unsigned int __flags) __THROW;
     ^~~~~~~~~~~~
/home/sirius/labs-proj/femu/rules.mak:69: recipe for target 'util/memfd.o' failed
```

The reason is that in femu/util/memfd.c:40:12 "static int memfd_create" is declared after "int memfd_create" has been declared in /usr/include/x86_64-linux-gnu/bits/mman-linux.h:115:0.

I rename "static int memfd_create" to "static int tmp_memfd_create" in femu/util/memfd.c:40:12 and compilation finishes successfully. 
So a rename to avoid double declaration is necessary.

**Comment by huaicheng** [comment]
Thanks for the feedback! I will try to verify this on Ubuntu 18.04.

**Comment by killerzula** [comment]
@BrightSirius  thanks a lot. You saved me from a lot of headache. However, as for your solution; wouldn't it cause problems further down the road as conveyed in the warning below
>/memfd.c:40:12: warning: ‘tmp_memfd_create’ defined but not used [-Wunused-function]
 static int tmp_memfd_create(const char *name, unsigned int flags)
            ^
