### ISSUE TITLE
Can I also use femu on Linux 4.10?

### ISSUE THREAD

**Issue by somnode** [ucare-uchicago/femu#20]
Can I also use femu on Linux 4.10?

**Comment by huaicheng** [comment]
Hi Somm,

FEMU depends on the "shadow doorbell buffer" feature for polling which is not supported by Linux 4.10 NVMe drivers, thus you cannot directly run 4.10 on FEMU.

The suggested Linux version to use with current FEMU is 4.14.

It's possible to run Linux 4.10 if you backport the "shadow doorbell buffer" patch (https://patchwork.kernel.org/patch/10259575/) from newer Linux version to 4.10.

**Comment by huaicheng** [comment]
I'm closing this issue, feel free to re-open it if you have more questions, thanks!
