### ISSUE TITLE
Run FEMU as an emulated blackbox SSD

### ISSUE THREAD

**Issue by cyb3727** [ucare-uchicago/femu#21]
Before I run the ./run-blackbox.sh, I delete the file vssd1.conf. I find that the femu still works with 1GB ssd device, why? Does the vssd1.conf file works on the 1GB ssd device? If not, how can I change the black box ssd setiing. Thanks!

**Comment by huaicheng** [comment]
Hi, 

Please keep the vssd1.conf configuration file for your virtual SSD, and modify parameters in it will change the SSD settings accordingly.

**Comment by cyb3727** [comment]
I have debug the source code of femu, and I found the bug. You have set the static parameters in ftl.c, and it doesn't read the parameters from vssd1.conf.

**Comment by huaicheng** [comment]
Oh, seems you are using the latest commit in the master branch, in that case, vssd1.conf is not needed as we add a new FTL. For this FTL, parameters about the virtual SSD are hard-coded so far as it's still on-going work.

Thanks.

**Comment by cyb3727** [comment]
Oh，I think you can submit the stable branch. I can only git the latest version. Thanks for your reply.
