### ISSUE TITLE
FEMU dies with "FEMU disabling NVMe Controller ..." message when performing fio with F2FS.

### ISSUE THREAD

**Issue by somnode** [ucare-uchicago/femu#22]
FEMU dies with "FEMU disabling NVMe Controller ..." message when performing fio with F2FS.
But FEMU doesn't die when performing fio with Ext4.

FEMU died when I performed the 6GB fio twice.

The fio option is (bs=4K, size=6G, numjobs=1, rw=write).
kernel version is 4.10.17 and I also tested at 4.15.0
I use FEMU checkout version ba56426057f57f7eab839e860c7672d5289e25c5.

I don't know what the problem is....

**Comment by huaicheng** [comment]
Could you try the latest commit using kernel 4.15.0 and see if the problem persists? And it will be helpful if you could share your guest kernel log when the problem happens.
