### ISSUE TITLE
OCSSD oob_meta Bug

### ISSUE THREAD

**Issue by ShiningNow1** [ucare-uchicago/femu#24]
When I tried to write and read  ocssd Sectors with oob_meta data, I found only the latest oob_meta data can be read correctly. So I read the code of femu_oc12.c and found no ppa offset is added to ln->meta_buf.

Here is the code:
```
int femu_oc_meta_write(FEMU_OC_Ctrl *ln, void *meta)
{
    memcpy(ln->meta_buf, meta, ln->params.sos);
    return 0;
}

int femu_oc_meta_read(FEMU_OC_Ctrl *ln, void *meta)
{
    memcpy(meta, ln->meta_buf, ln->params.sos);
    return 0;
}

```
no ppa offset is added to ln->meta_buf. So I wish you can fix it as quickly as possible. Thanks

**Comment by huaicheng** [comment]
Thanks for reporting this bug. Will fix it in the next FEMU version.
