### ISSUE TITLE
How can I emulate multiple nvme devices ?

### ISSUE THREAD

**Issue by MetalheadKen** [ucare-uchicago/femu#26]
HI. Thanks for creating this software first.

I'm tring to emulate multiple blackbox SSDs in FEMU.
Is there any way to implement it ?
Thanks again for your help :)

**Comment by huaicheng** [comment]
Add multiple femu options in the VM script will give you multiple FEMU devices, e.g.
 
```
  -device femu,devsz_mb=1024,femu_mode=1 \
  -device femu,devsz_mb=1024,femu_mode=1 \
  ...
```

The above command lines give you two femu ssds (size of 1GB each).

**Comment by MetalheadKen** [comment]
It's very helpful to me.
Thanks a million!
