### ISSUE TITLE
Does the FTL in blackbox mode decied where write command end up?

### ISSUE THREAD

**Issue by Pihlqvist** [ucare-uchicago/femu#27]
Hello

I'm wondering if the FLT in blackbox mode have an impact on how the underlying memory is emulated, or if it's only used for statistical means.

As far as I see it the `NvmeRequest` that is passed through the FTL and then sent to the poller don't change the address. I'm I wrong in thinking this?

**Comment by huaicheng** [comment]
I'm not sure if I understand the question correctly. The write addr (LBA) passed to the FTL will be mapped to a physical flash page address in the FTL thread. Actually the FTL mainly needs (addr, length) fields from ``NvmeRequest`` to emulate an IO. These are processed internally inside the FTL, ``NvmeRequest`` is the IO unit for the NVMe layer emulation.
