### ISSUE TITLE
FEMU disabling NVMe Controller  nvme_add_kvm_msi_virq,cq[1]->virq=27

### ISSUE THREAD

**Issue by wuqiulin1995** [ucare-uchicago/femu#30]
Hi
I run FEMU as a black box (formated F2FS) and run randomwrite workload of filebench for a few minutes.
The guest linux kernel is 4.15.1 and the FEMU version is [ba56426](https://github.com/ucare-uchicago/femu/commit/ba56426057f57f7eab839e860c7672d5289e25c5)
The following information is printed on the terminal:

"FEMU disabling NVMe Controller ...
Coperd, CQ, db_addr=5268549644, eventidx_addr=5270683660
Coperd,nvme_add_kvm_msi_virq,cq[1]->virq=27
Coperd, SQ, db_addr=5268549640, eventidx_addr=5270683656"

What problem is it and how can I solve it?

**Comment by huaicheng** [comment]
Hi,

Thanks for reporting this! I noticed you were using a relatively old commit. Could you try the latest commit and see if the problem still persists?

The above problem seems to indicate that somehow FEMU NVMe controller was reset, and it couldn't associate virq with nvme queue pairs correctly.
