### ISSUE TITLE
Emulate a large SSD

### ISSUE THREAD

**Issue by cyb3727** [ucare-uchicago/femu#33]
When I emulate a disk of 256GB, it is ok. But when I emulate a disk of 512GB, it has error "Invalid State!" while reading or writing.
ftl.c settings is shown as following:   
512GB
    spp->secsz = 512;
    spp->secs_per_pg = 8;
    spp->pgs_per_blk = 1024;
    spp->blks_per_pl = 1024; /* 16GB */
    spp->pls_per_lun = 1;
    spp->luns_per_ch = 32;
    spp->nchs = 4;
256GB
    spp->secsz = 512;
    spp->secs_per_pg = 8;
    spp->pgs_per_blk = 1024;
    spp->blks_per_pl = 1024; /* 16GB */
    spp->pls_per_lun = 1;
    spp->luns_per_ch = 32;
    spp->nchs = 2;

**Comment by newcloudsu** [comment]
Did you solve it ?
