### ISSUE TITLE
How to input req to make the simulator feedback the result?

### ISSUE THREAD

**Issue by Faker-LL** [ucare-uchicago/femu#34]
Hi,maintainer
I run a black box script, how do I input the ssd read/write request to get the result, do I need any other tools?
Can you tell me how to use this emulator？
![image](https://user-images.githubusercontent.com/52771354/90227907-ebe63b80-de47-11ea-9232-290f1c6b0bfb.png)

**Comment by huaicheng** [comment]
You should be able to see the device "/dev/nvme0n1" (or similar), then issue I/Os (using "fio" or other IO benchmark tools) to this device will trigger the FEMU side SSD emulation logic.
