### ISSUE TITLE
Bandwidth with differential channels

### ISSUE THREAD

**Issue by cyb3727** [ucare-uchicago/femu#35]
I have set the ssd parameters as following, and then test the bandwidth with comand:
sudo time dd if=/dev/nvme0n1 of=/dev/null bs=8k count=1024. I seems that the bandwidth is almost all the same. Why?
  spp->secsz = 512;
    spp->secs_per_pg = 8;
    spp->pgs_per_blk = 256;
    spp->blks_per_pl = 1024; /* 64GB */
    spp->pls_per_lun = 1;
    spp->luns_per_ch = 8;
    spp->nchs = 2 or 10;

**Comment by huaicheng** [comment]
What's the bandwidth reported by ``dd``? Did you warm up the emulated SSD by doing sequential writes to it first before reading it back? 

Every time you reboot the VM, the emulated will be treated as a ``brand new`` device with no data stored in it at all, thus if you read from the empty device, it will return immediately.
