### ISSUE TITLE
How to RUN FEMU

### ISSUE THREAD

**Issue by DanlinJia** [ucare-uchicago/femu#36]
I compiled femu and downloaded the FEMU-VM image as you provided.
Could you show the detailed instructions about how to run femu?
Cause I'm a noobie to QUME, is there any reference that helps me be familiar with the whole system?

Thanks

**Comment by davidkmw0810** [comment]
Hello DanlinJia.
I couldn't run FEMU now. I'm a noobie to QUME too.
Did you solve you're problem? If you solved, could you share the problem and solution?
