### ISSUE TITLE
How to profile SSD-related information?

### ISSUE THREAD

**Issue by geonheec** [ucare-uchicago/FEMU#37]
I want to monitor the SSD related information in FEMU.
For example, I want to store the Write amplification factor (WAF)  in ftl and check the value after benchmarking.

Is there a way to check the value of a specific variable stored by FEMU?

**Comment by huaicheng** [comment]
Sorry for the late reply. Currently the public version of FEMU FTL doesn't have those statistics/counters. We will push those features later on.
