### ISSUE TITLE
pblk mydevice: corrupted read LBA (0/xxxxx)

### ISSUE THREAD

**Issue by lovers-under-moon** [ucare-uchicago/FEMU#49]
When I test OCSSD2.0 write and read using fio,the pblk mydevice: corrupted read LBA (0/xxxxx) appeared.

This is the script I used for testing.

#!/bin/bash
sudo insmod /lib/modules/5.4.0-70-generic/kernel/drivers/lightnvm/pblk.ko
sudo nvme lnvm create -d nvme0n1 -n mydevice -t pblk -b 0 -e 7
#100%随机，70%读，30%写 4K
sudo fio -filename=/dev/mydevice -direct=1 -iodepth 1 -thread -rw=randrw -rwmixrread=70 -ioengine=psync -bs=4k -size=2G -numjobs=50 -runtime=180 -group_reportingg -name=randrw_70read_4k

![image](https://user-images.githubusercontent.com/45291298/114514097-8152fd00-9c6d-11eb-85b8-0e8506dec50c.png)

**Comment by huaicheng** [comment]
It's a known FEMU bug, not critical though. If you want those warning msgs go away, just comment out the corresponding line of code in lightnvm and recompile your guest kernel. It doesn't affect the data correctness.
