### ISSUE TITLE
It looks like TRIM(DISCARD) request is being processed like a READ request.

### ISSUE THREAD

**Issue by geonheec** [ucare-uchicago/FEMU#53]
I am modifying FEMU to support TRIM(DISCARD) function. (for bbssd)
By the way, it looks like TRIM(DISCARD) request is being processed like a READ request.
(Of course, when mounting on the FEMU, there is no problem at all unless you use the `-o discard` option. This issue only occurs when the `-o discard` option is used.)

See the `nvme_process_sq_io` function in `FEMU/hw/block/femu/nvme-io.c`.
It seems that all requests returning NVME_SUCCESS from `nvme_io_cmd` are forwarded to the FTL thread.

However, since DSM requests (that are not READ/WRITE requests) also return NVME_SUCCESS from the `nvme_io_cmd` function, as a result, they are transferred to the FTL thread and are processed as if they were read requests. (since `is_write` variable is 0)

Of course, this does not involve data DMA to the host, but it increases the latency of the lun as much as processing the read request, which can make the emulation result inaccurate. (This is because FTL processes READ to lun even though the host's READ request has not occurred.)

So, if you have no plan to support TRIM(DISCARD), FTL threads will probably need modifications like invalidating DSM requests.
(Among DSM requests, I know that the request with the NVME_DSMGMT_AD attribute is the DISCARD request.)

Could you please review if my analysis is correct? 
I'm not familiar with the QEMU and NVMe protocols, so maybe my analysis was wrong.

**Comment by huaicheng** [comment]
Hi,

Thanks for reporting this! Yes, your analysis is correct! The ``ftl_thread()`` can be tuned to filter out non-necessary IO commands and handle them in a fast-path to avoid the above issues. Will fix this later.

**Comment by huaicheng** [comment]
Added a temporary fix. It should be easy to extend the FEMU thread to process more types of I/O requests when needed.
