### ISSUE TITLE
FEMU compilation error due to meson

### ISSUE THREAD

**Issue by manojps** [ucare-uchicago/FEMU#56]
I am getting the following error when compiling FEMU. 

```
../tests/qtest/meson.build:73:2: ERROR: No program name specified.

A full log can be found at /media/sdd/KVDM/FEMU/build-femu/meson-logs/meson-log.txt

ERROR: meson setup failed

config-host.mak is out-of-date, running configure
bash: line 3: ./config.status: No such file or directory
make: *** No rule to make target 'config-host.mak', needed by 'meson.stamp'.  Stop.

===> FEMU compilation done ...
```
My machine setup is as follows.
OS: ubuntu1~16.04.12
Kernel: 4.4.0-210-generic
GCC: 5.4.0
Ninja: 1.10.2 
Python: 3.8.5

I have tried the solution at this page https://bugs.launchpad.net/qemu/+bug/1892533 to no avail. 

Could you please suggest how to resolve the issue?

**Comment by fengxidi** [comment]
Hello, I also encountered this problem. My solution is to delete the meson command first, and then reinstall it. It is solved

**Comment by manojps** [comment]
I solved the issue by creating new Anaconda environment with Python 3.6, and installing Meson 1.8.2 according to the tested system table in the Readme in the FEMU repository.
