### ISSUE TITLE
Looking for a way to modify the characteristics of flash device

### ISSUE THREAD

**Issue by HongweiQin** [ucare-uchicago/femu#6]
Hi, 
I'm using FEMU to emulate a whitebox SSD. 
Is there a way to modify the characteristics (e.g. page read/write latency, block erase latency) of the emulated flash device? 
Thanks in advance.

**Comment by huaicheng** [comment]
Yes, you can use the following methods:

(1). In hw/block/femu/femu-oc.c, line 78-83 defines the default latency numbers for page read/program and block erase, profiled from our CNEX OCSSD. You can modify them directly and recompile FEMU.

(2). A more convenient way requires no femu code change. FEMU already defines a NVMe command (opcode: 0xee) for you to change the latency characteristics in flight. You can use the command ``admin-passthru`` subcommand provided by ``nvme-cli`` tool, for example,
```
$ sudo nvme admin-passthru -d /dev/nvme0n1 --opcode=0xee --cdw10=1 --cdw11=2 --cdw12=3 --cdw13=4 --cdw14=5 --cdw15=6
```
Where:
  - cdw10=1; set NAND upper page read latency to 1ns
  - cdw11=2; set NAND lower page read latency to 2ns
  - cdw12=3; set NAND upper page program latency to 3ns
  - cdw13=4; set NAND lower page program latency to 4ns
  - cdw14=5; set NAND block erase time to 5ns
  - cdw15=6; set time of channel transferring one page to 6ns

Hope this helps.

**Comment by HongweiQin** [comment]
@huaicheng Thanks for your help.
BTW, if I set those values into a pretty low point, should I consider the latency of DRAM?
For example, if I set the read latency to L, is the actual latency L or L+Ldram?

**Comment by huaicheng** [comment]
It's L. FEMU delay emulation logics already counts in all the software overhead, including I/O emulation + DRAM access. If you set them to a very small value (e.g. less than the software overhead itself), you won't get accurate latency emulation.
