### ISSUE TITLE
FEMU fails with guest kernel 4.16

### ISSUE THREAD

**Issue by DanlinJia** [ucare-uchicago/FEMU#64]
Greeting!

I'm using FEMU as an emulator in one VM. I need to install a driver on the VM but it only supports specific kernel versions (4.13 and 4.15). Therefore, I attempted to create images with kernel 4.13 following the instruction in README, as I knew FEMU is not compatible with kernel 4.15. However, when I appended the FEMU device to the QEMU VM, I got errors about NVMe related errors. 

As the README says FEMU works with guest kernel version 4.16, 4.20, 5.4 and 5.10 for the black box mode, I tested on each version but found FEMU only works with kernel 5.4 and 5.10. The boot process pops the same error as I got in the test of kernel 4.13.

I think the reason causing booting with kernel 4.16 & 4.20 failed also prevents the VM boot with kernel 4.13 in the blackbox mode. I wonder if anyone can help me to check if my image creation is wrong or I miss any parameters in the whole procedure. 

Testbed:
>QEMU version 5.2.0
Guest kernel version 4.16

GRUB config:
> GRUB_DEFAULT=0
GRUB_TIMEOUT_STYLE=hidden
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`
GRUB_CMDLINE_LINUX_DEFAULT="maybe-ubiquity"
GRUB_CMDLINE_LINUX=""
GRUB_CMDLINE_LINUX="ip=dhcp console=ttyS0,115200 console=tty console=ttyS0"
GRUB_TERMINAL=serial
GRUB_SERIAL_COMMAND="serial --unit=0 --speed=115200 --word=8 --parity=no --stop=1"

QEMU Command:
`sudo x86_64-softmmu/qemu-system-x86_64 \
    -name "FEMU-BBSSD-VM" \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -m 4G \
    -device virtio-scsi-pci,id=scsi0 \
    -device scsi-hd,drive=hd0 \
    -drive file=/home/danlin/images/u18.qcow2,if=none,aio=native,cache=none,format=qcow2,id=hd0 \
    -device femu,devsz_mb=4096,femu_mode=1 \
    -net user,hostfwd=tcp::6432-:22 \
    -net nic,model=virtio \
    -qmp unix:./qmp-sock,server,nowait 2>&1 | tee log \
` 

Error messages:
>1.213700] Freeing unused kernel memory: 2008K
[ 1.217629] Freeing unused kernel memory: 1900K
1.2230241 x86/mm: Checked W+X mappings: passed, no W+8 pages found.
1.2240821 x86/mm: Checking user space page tables
1.232831] x86/mm: Checked W+X mappings: passed, no W+X pages found.
1.344019) Floppy drive(s): fdo is 2.88M AMI BIOS
1.367409] FDC O is a S82078B
1.3693521 piix4_smbus 0000:00:01.3: SMBus Host Controller at Ox700, revisio
1.373780] cryptd: max_cpu_qlen set to 1000
[ 1.374790] virtio_net virtioo ens3: renamed from etho
1.376688] input: Virtua1PS/2 VMware VMMouse as /devices/platform/i8042/seri
01/input/input4
[ 1.379200] input: VirtualPS/2 VMware VMMouse as /devices/platform/i8042/seri
01/input/input3
[ 1.391903] AVX2 version of gcm_enc/dec engaged.
[ 1.395810) AES CTR mode by8 optimization enabled
[ 1.9201001 tsc: Ref ined Tsc clocksource calibration: 3407.975 MHz
1.921275] clocksource: tsc: mask: Oxffffffffffffffff max_cycles: 0x311fbc3c
54f, max_idle_ns: 440795216628 ns
31.856070] nyme nume: 1/0 215 QID 1 timeout, aborting
31.8570221 nvme nvme: Abort status: Oxo
61.936068] nyme nume: 1/0 215 QID 1 timeout, reset controller
92.848071) nvme nvme: 1/0 215 QID 1 timeout, disable controller
[242.763376]
schedule_preempt_disabled+oxe/0x10
__mutex_lock.isra. 2+0x18c/0x4do
? __switch_to_asm+0x34/0x70
? __switch_to_asm+0X40/0x70
_mutex_lock_slowpath+0x13/0x20
? __mutex_lock_slowpath+0x13/0x20
mutex_lock+0x2f/0x40
nvme_stop_queues+0x21/0x50
nyme_dev_disable+0x280/0x490
? dev_warn+0x64/0x80
? schedule+0x2c/0x80
nvme_timeout+0x240/0x2f0
blk_mq_terminate_expired+0X4f/0x90
bt_iter+0X4c/0x60
blk_mq_queue_tag_busy_iter+0x162/0x260
? blk_mq_add_to_requeue_list+0xC0/0XCO
? blk_mq_add_to_requeue_list+0xc0/OXCO
blk_mq_timeout_work+oxea/0x160
process_one_work+0x1de/0x3e0
worker_thread+0x32/0x410
kthread+0x121/0x140
? process_one_work+0x3e0/0x3e0
? Kthread_create_worker_on_cpu+0x70/0x70
ret_from_fork+0x35/0x40

**Comment by huaicheng** [comment]
Hi,

Thanks for reporting this. 

I pushed a few fixes and my local tests runs fine on guest kernels 4.15, 4.16, 4.20 and 5.10 under blackbox mode. Git pull, recompile FEMU and try it again on your end. Let me know if it works for you.

I will also share a VM image with more guest kernel verions included, keep an eye on the README changes if you prefer to use it.
