### ISSUE TITLE
Key-Value SSD emulator

### ISSUE THREAD

**Issue by davidkmw0810** [ucare-uchicago/FEMU#68]
Hello I'm a M.S student to research KV-SSD.

I want to use FEMU on Key-Value SSD for improve mapping algorithm.
But FEMU doesn't have any Key-Value things.
I think I have to edit FEMU for research KV-SSD.
What I have to edit for KV-SSD emulating?

**Comment by huaicheng** [comment]
As of now, FEMU doesn't support acting as a KVSSD. PRs are welcome!

You can add a "KVSSD" mode to FEMU, similarly to how the existing FEMU supports different types of SSDs. 

One might be able to port some of the implementations here: https://github.com/OpenMPDK/KVSSD to FEMU context.

**Comment by davidkmw0810** [comment]
Thank you.
