### ISSUE TITLE
Overhead of writing doorbell on Guest OS

### ISSUE THREAD

**Issue by zhengwei6** [ucare-uchicago/FEMU#69]
I’m a graduate student majoring in Computer Science. I would be grateful if you give me some suggestions.
I want to ask the question about the overhead of writing a doorbell on Guest OS using FEMU. According to the paper, it just needs to write the memory address of Guest OS without VM exit, but it still has 6.5 us (avg), 5.7 us (median), and 18.9 us (std) time intervals in my experiment. I expect the time should be one memory access time. I calculated the time interval for each writing doorbell event in the nvme_write_sq_db function (based on Linux Kernel v5.10.11 /drivers/nvme/host/pci.c ) running on FEMU. 
- The following is how I calculate the time interval for this function.
![Screenshot from 2022-02-17 18-58-44](https://user-images.githubusercontent.com/40619175/154511748-8f671ffa-0c6f-4800-827a-327ddeb516b6.png)
- The following is the result.
![unnamed](https://user-images.githubusercontent.com/40619175/154511846-84111261-3d12-43d2-87ce-0bd991ca2593.png)
![unnamed (1)](https://user-images.githubusercontent.com/40619175/154511872-7d7e6e1d-6f87-4b73-8e45-9446a690fcdb.png)
Thanks!

**Comment by huaicheng** [comment]
Check the "Addtional (Optional) Tweaks" section here: https://github.com/ucare-uchicago/FEMU/wiki/FEMU-Best-Practice

You're right that MMIO writes are heavy ops from guest OS. FEMU significantly reduces the # of such MMIO writes (or completely eliminates them when you apply the above one line of NVMe driver code change), but FEMU doesn't optimize the overhead of MMIO itself.

**Comment by zhengwei6** [comment]
Thanks! I got it. I will try to apply the one line of NVMe driver code change.
