### ISSUE TITLE
Latency fluctuation observed

### ISSUE THREAD

**Issue by HongweiQin** [ucare-uchicago/femu#7]
Hi,
After running FEMU as a white box, I use a self-defined kernel module to measure the actual latency of requests. The kernel module creates N kernel threads where N equals to the number of LUN. For each thread, it first erase the whole corresponding LUN and then generates write requests targeting at sequential pages inside that LUN.
I observe some latency fluctuation. Especially for the first write request(up to tens of milliseconds). Have you noticed this issue? I assume it is caused by the host page fault?

**Comment by HongweiQin** [comment]
I created 8 channels and 4LUNs per channel. 
My module submit commands using nvm_submit_io(). 
Since the design goal of my module is to test the maximum bandwidth of the device, the module doesn't register as a block device. As a result, I can't run fio upon it. 
I think I can give you my test code and scripts by email.

**Comment by huaicheng** [comment]
That's the problem.

nvm_submit_io() will potentially issue erase for the first write in a block when u do writes (even though u erased the block in advance, lightnvm doesn't think so).

**Comment by HongweiQin** [comment]
@huaicheng 
Hi,
According to my test, I didn't find any unexpected erase request. Can you provide more details about how does nvm_submit_io() issue erase for the first write in a block?
**My test method:** 
Just like what I did previously, I use a kernel module named rgen to issue requests. 
SSD's configuration: 32 channels, 4 LUNs per channel.
I use printk to print out the time before nvme_queue_rq() returns.
I also use printk to print out the time nvme_queue_rq() executes.
**My test result:** 
If only 1 thread is created: 
        Every thing goes fine and no abnormal latency is observed.
If 32 threads are created: 
        Every erase request completes in about **5ms**. (Which is normal)
        For the 1st write of each thread, the latency is about **23ms**.(Which is weird)
        For the 1st write of each thread, only 1 _struct nvme_command cmnd_ is issued.
        For the 2nd write of each thread, the latency is about **1ms**.(Which is normal)
**My suspect:** 
       Probably I ignored some details. 
       Probably I've found a bug.
       If you're interested, I'm willing to provide my test code.
