### ISSUE TITLE
Connection information between block driver and femu

### ISSUE THREAD

**Issue by ggyuchoe** [ucare-uchicago/FEMU#72]
Hello. 
I am a M.S. student who has recently become interested in ZNS and wants to do research.

I would like to use the block driver's write_hint information (e.g., block driver's bio_write_hint) in femu to conduct research,
but would you mind if I ask which part of the block driver is connected to the nvme command that femu receives and how it matches?

**Comment by huaicheng** [comment]
Could you be more specific about what kind of "hint" information you're referring to? Is it already supported by NVMe spec? FEMU follows the standard NVMe protocol to process all the submission commands and I don't recall there are such logics at the FEMU level (Please point it out if I'm wrong). You might want to check how the OS block IO stack and NVMe driver handles such information and use them to compose NVMe commands.

**Comment by ggyuchoe** [comment]
I think I asked too vaguely.
In practice, I would like to explicitly add the data&node's temperature information (hot/warm/cold) of the f2fs file system to the nvme command (or submission queue entry) and use it inside the ssd.
It seems that this information is used up to the block device driver layer (bio_write_hint, which was previously asked), but it seems that the information is not transmitted on the nvme command spec.
So, I wanted to know the information to which part of the actual O/S is applied as guest O/S and from which part the femu code is applied. (If I knew this part, I thought it would be a hint on which part of the information could be added if I modified it.)
