### ISSUE TITLE
How to configure the sector size in FEMU ZNS mode?

### ISSUE THREAD

**Issue by Haltz** [ucare-uchicago/FEMU#76]
I want to modify the sector size in FEMU ZNS mode from 512B to 4KiB. I suppose the `id_ns->flbas` has something to do with it(the `lbads`, which is log2(sector_size) i think, is based on the `id_ns->flbas` from `static inline NvmeLBAF *zns_ns_lbaf(NvmeNamespace *ns)` in `zns.h`). However, i didn't find a way to configure it. So anyone can help me? Thanks very much!

**Comment by Haltz** [comment]
I'm sorry that it seems not woking. After changing lba_index from 0 to 2, the device is invisible in the guest vm. I will dive deeper into the issue. Thank you very much.

**Comment by Haltz** [comment]
Hi, huaicheng. I think we also need to change the following code besides your suggestion.
https://github.com/ucare-uchicago/FEMU/blob/b388b400e7363a0eb20c1c726114ebe6aab374b1/hw/femu/zns/zns.c#L137
https://github.com/ucare-uchicago/FEMU/blob/b388b400e7363a0eb20c1c726114ebe6aab374b1/hw/femu/zns/zns.c#L138

I think replacing `lba_index` with `n->lba_index` is necessary.

Is that your typo mistake😀?

**Comment by UNKJay** [comment]
@Haltz 
Hello, I also want to onfigure the sector size in FEMU ZNS mode, do you know how to do ?
Thank you very much.

**Comment by Haltz** [comment]
> @Haltz Hello, I also want to onfigure the sector size in FEMU ZNS mode, do you know how to do ? Thank you very much.

Hi, @UNKJay. Have you tried the solution mentioned above?

**Comment by UNKJay** [comment]
@Haltz Thank you for your solution, I've fix the problem.
