### ISSUE TITLE
How can I get various info about the device internal state and behavior? 

### ISSUE THREAD

**Issue by dujingwen** [ucare-uchicago/femu#8]
Hi,
     I want to get some values like erase count,  device space usage ratio,  migration page count during garbage collection , L2P mapping info and so on. But how can I print or view/check this info? Thanks in advance.

**Comment by WaterccL** [comment]
The struct **ssdstate** consists of written_page number.
```
     /* SSD Util */
    double ssd_util;
    int64_t written_page_nb;

    /* Mapping table */
    int64_t *mapping_table;
```
If you want to print such information, you may need to modify the source code and recompile it.

**Comment by theanoli** [comment]
It seems the ssdstate struct isn't around anymore (and I can't find a page write counter elsewhere). If I wanted to track the number of page writes, would it be best to put the counter in the `NANDFlashState` struct, and then increment the counter in the `nand_blk_write_` function ([here](https://github.com/ucare-uchicago/femu/blob/34b3567d277a13357c4849208a3aaaabf874a472/hw/block/nand.c#L662))?

**Comment by huaicheng** [comment]
Hi,

You might want to check code under ``hw/block/femu/ftl/``.  The ideal place to add the counter you need is ``ssd_advance_status()``, which is called every time a NAND level I/O needs to be triggered.
