### ISSUE TITLE
Dose ssd emulator support TRIM?

### ISSUE THREAD

**Issue by hookak** [ucare-uchicago/femu#9]
Hi,
I'm looking at code that emulates an ssd device.
Then, TRIM related code in '/femu/hw/block/ssd/ssd_trim_manager.c' had been commented.
Does not yet support the trim command in emulator?

**Comment by huaicheng** [comment]
No, that part of code is inherited from VSSIM, which doesn't support TRIM neither.

But it's a good point, I will add it to my TODO list.
